import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";


const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={poppins.className}>
        {children}
      <footer className="w-full flex justify-center items-center py-8 px-4">
        <span className="text-center text-[14px] text-primary-200 font-medium ">© 2024 Manuel Villarroel. Todos los derechos reservados.</span>
      </footer>
      </body>
    </html>
  );
}
